---
label: Project
hide_body: false
display_field: title
fields:
- type: text
  name: title
  label: title
- type: tag_list
  name: categories
  label: categories
- type: datetime
  name: date
  label: date
- type: text
  name: author
  label: author
  description: 'Ex: John Doe'
- type: file
  name: image
  label: image
- type: text
  name: description
  label: description
  description: meta description
- type: text
  name: project_url
  label: project url
  description: Project Url
pages:
- exampleSite/content/portfolio/potato-stats.md
- exampleSite/content/portfolio/potato-test.md
- exampleSite/content/portfolio/test3.md
