---
label: Project
hide_body: false
display_field: project_url
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- type: text
  name: author
  label: author
  description: 'Ex: John Doe'
- type: file
  name: image_webp
  label: image webp
- type: file
  name: image
  label: image
- type: text
  name: description
  label: description
  description: meta description
- type: text
  name: project_url
  label: project url
  description: Project Url
- type: boolean
  name: draft
  label: draft
  description: draft
pages:
- exampleSite/content/portfolio/potato-test.md
